const express = require('express');

const router = express.Router();

// 300 Unique Motivational Quotes
const motivationalQuotes = [
  "The only way to do great work is to love what you do.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Believe you can and you're halfway there.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It does not matter how slowly you go as long as you do not stop.",
  "You are never too old to set another goal or to dream a new dream.",
  "The only impossible journey is the one you never begin.",
  "In the middle of difficulty lies opportunity.",
  "The way to get started is to quit talking and begin doing.",
  "Don't watch the clock; do what it does. Keep going.",
  "You don't have to be great to start, but you have to start to be great.",
  "The secret of getting ahead is getting started.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big things happen.",
  "It's going to be hard, but hard does not mean impossible.",
  "Don't wait for opportunity. Create it.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream it. Believe it. Build it.",
  "If you want to achieve greatness stop asking for permission.",
  "Things work out best for those who make the best of how things work out.",
  "To live a creative life, we must lose our fear of being wrong.",
  "If you are not willing to risk the usual you will have to settle for the ordinary.",
  "Trust because you are willing to accept the risk, not because it's safe or certain.",
  "Take up one idea. Make that one idea your life.",
  "All our dreams can come true if we have the courage to pursue them.",
  "Good things come to people who wait, but better things come to those who go out and get them.",
  "If you do what you always did, you will get what you always got.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Just when the caterpillar thought the world was ending, he turned into a butterfly.",
  "Successful entrepreneurs are givers and not takers of positive energy.",
  "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.",
  "Opportunities don't happen, you create them.",
  "Try not to become a person of success, but rather try to become a person of value.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "If you don't value your time, neither will others. Stop giving away your time and talents—start charging for it.",
  "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
  "No one can make you feel inferior without your consent.",
  "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.",
  "If you're going through hell keep going.",
  "The ones who are crazy enough to think they can change the world, are the ones who do.",
  "Don't raise your voice, improve your argument.",
  "What seems to us as bitter trials are often blessings in disguise.",
  "The meaning of life is to find your gift. The purpose of life is to give it away.",
  "The distance between insanity and genius is measured only by success.",
  "When you stop chasing the wrong things you give the right things a chance to catch you.",
  "Don't be afraid to give up the good to go for the great.",
  "No masterpiece was ever created by a lazy artist.",
  "Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you.",
  "If you can't explain it simply, you don't understand it well enough.",
  "Blessed are those who can give without remembering and take without forgetting.",
  "Do one thing every day that scares you.",
  "What's the point of being alive if you don't at least try to do something remarkable.",
  "Life is not about finding yourself. Life is about creating yourself.",
  "Nothing in the world is more common than unsuccessful people with talent.",
  "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it.",
  "Your problem isn't the problem. Your reaction is the problem.",
  "You can do anything, but not everything.",
  "Innovation distinguishes between a leader and a follower.",
  "There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.",
  "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life.",
  "People who are crazy enough to think they can change the world, are the ones who do.",
  "We become what we think about most of the time, and that's the strangest secret.",
  "The best way to not feel hopeless is to get up and do something. Don't wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope.",
  "The person who says it cannot be done should not interrupt the person who is doing it.",
  "There are no traffic jams along the extra mile.",
  "It is never too late to be what you might have been.",
  "You become what you believe.",
  "I would rather die of passion than of boredom.",
  "A truly rich man is one whose children run into his arms when his hands are empty.",
  "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.",
  "If you want your children to turn out well, spend twice as much time with them, and half as much money.",
  "Build your own dreams, or someone else will hire you to build theirs.",
  "The battles that count aren't the ones for gold medals. The struggles within yourself—the invisible battles inside all of us—that's where it's at.",
  "Education costs money. But then so does ignorance.",
  "The most important thing is to try and inspire people so that they can be great in whatever they want to do.",
  "Fall seven times and stand up eight.",
  "The real opportunity for success lies within the person and not in the job.",
  "Every accomplishment starts with the decision to try.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.",
  "Start where you are. Use what you have. Do what you can.",
  "The journey of a thousand miles begins with one step.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to discover the limits of the possible is to go beyond them into the impossible.",
  "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The person who moves a mountain begins by carrying away small stones.",
  "If you want to lift yourself up, lift up someone else.",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "Nothing is impossible, the word itself says 'I'm possible'!",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "You may encounter many defeats, but you must not be defeated.",
  "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
  "What we achieve inwardly will change outer reality.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Be yourself; everyone else is already taken.",
  "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "You will face many defeats in life, but never let yourself be defeated.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "In the end, it's not the years in your life that count. It's the life in your years.",
  "Never let the fear of striking out keep you from playing the game.",
  "Life is either a daring adventure or nothing at all.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
  "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.",
  "It is during our darkest moments that we must focus to see the light.",
  "Whoever is happy will make others happy too.",
  "Always remember that you are absolutely unique. Just like everyone else.",
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "When you reach the end of your rope, tie a knot in it and hang on.",
  "Life is what happens to you while you're busy making other plans.",
  "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
  "Your time is limited, so don't waste it living someone else's life.",
  "Don't be trapped by dogma — which is living with the results of other people's thinking.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
  "Stay hungry. Stay foolish.",
  "If you haven't found it yet, keep looking. Don't settle.",
  "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future.",
  "It's fine to celebrate success but it is more important to heed the lessons of failure.",
  "Only the paranoid survive.",
  "People who are serious about software should make their own hardware.",
  "If you are working on something exciting that you really care about, you don't have to be pushed. The vision pulls you.",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character.",
  "Don't let yesterday take up too much of today.",
  "The people who are crazy enough to think they can change the world are the ones who do.",
  "The purpose of our lives is to be happy.",
  "Get busy living or get busy dying.",
  "You have to expect things of yourself before you can do them.",
  "The only impossible journey is the one you never begin.",
  "In order to succeed, we must first believe that we can.",
  "A person who never made a mistake never tried anything new.",
  "The person who says it cannot be done should not interrupt the person who is doing it.",
  "There are no traffic jams along the extra mile.",
  "It is never too late to be what you might have been.",
  "You become what you believe.",
  "I would rather die of passion than of boredom.",
  "A truly rich man is one whose children run into his arms when his hands are empty.",
  "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.",
  "If you want your children to turn out well, spend twice as much time with them, and half as much money.",
  "Build your own dreams, or someone else will hire you to build theirs.",
  "The battles that count aren't the ones for gold medals. The struggles within yourself—the invisible battles inside all of us—that's where it's at.",
  "Education costs money. But then so does ignorance.",
  "The most important thing is to try and inspire people so that they can be great in whatever they want to do.",
  "Fall seven times and stand up eight.",
  "The real opportunity for success lies within the person and not in the job.",
  "Every accomplishment starts with the decision to try.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.",
  "Start where you are. Use what you have. Do what you can.",
  "The journey of a thousand miles begins with one step.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to discover the limits of the possible is to go beyond them into the impossible.",
  "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The person who moves a mountain begins by carrying away small stones.",
  "If you want to lift yourself up, lift up someone else.",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "Nothing is impossible, the word itself says 'I'm possible'!",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "You may encounter many defeats, but you must not be defeated.",
  "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
  "What we achieve inwardly will change outer reality.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Be yourself; everyone else is already taken.",
  "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.",
  "The purpose of our lives is to be happy.",
  "Get busy living or get busy dying.",
  "You have to expect things of yourself before you can do them.",
  "In order to succeed, we must first believe that we can.",
  "A person who never made a mistake never tried anything new.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You miss 100% of the shots you don't take.",
  "Whether you think you can or you think you can't, you're right.",
  "The future depends on what you do today.",
  "It always seems impossible until it's done.",
  "Act as if what you do makes a difference. It does.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Be the change that you wish to see in the world.",
  "Find out who you are and do it on purpose.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "The only true wisdom is in knowing you know nothing.",
  "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
  "Do what you can, with what you have, where you are.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
  "As we look ahead into the next century, leaders will be those who empower others.",
  "The best preparation for tomorrow is doing your best today.",
  "Happiness is not something readymade. It comes from your own actions.",
  "For every minute you are angry you lose sixty seconds of happiness.",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "The only person you need to be better than is the person you were yesterday.",
  "Don't let the fear of losing be greater than the excitement of winning.",
  "If you want to make your dreams come true, the first thing you have to do is wake up.",
  "The only thing worse than being blind is having sight but no vision.",
  "The way to get started is to quit talking and begin doing.",
  "Don't let yesterday take up too much of today.",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character.",
  "If you are working on something exciting that you really care about, you don't have to be pushed. The vision pulls you.",
  "People who are serious about software should make their own hardware.",
  "Innovation distinguishes between a leader and a follower.",
  "The secret of getting ahead is getting started.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Only the paranoid survive.",
  "It's fine to celebrate success but it is more important to heed the lessons of failure.",
  "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future.",
  "If you haven't found it yet, keep looking. Don't settle.",
  "Stay hungry. Stay foolish.",
  "The people who are crazy enough to think they can change the world are the ones who do.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
  "The only way to do great work is to love what you do.",
  "Don't be trapped by dogma — which is living with the results of other people's thinking.",
  "Your time is limited, so don't waste it living someone else's life.",
  "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
  "Life is what happens to you while you're busy making other plans.",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "When you reach the end of your rope, tie a knot in it and hang on.",
  "Always remember that you are absolutely unique. Just like everyone else.",
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
  "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.",
  "It is during our darkest moments that we must focus to see the light.",
  "Whoever is happy will make others happy too.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "You will face many defeats in life, but never let yourself be defeated.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "In the end, it's not the years in your life that count. It's the life in your years.",
  "Never let the fear of striking out keep you from playing the game.",
  "Life is either a daring adventure or nothing at all.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  "The only impossible journey is the one you never begin.",
  "In order to succeed, we must first believe that we can.",
  "A person who never made a mistake never tried anything new.",
  "The person who says it cannot be done should not interrupt the person who is doing it.",
  "There are no traffic jams along the extra mile.",
  "It is never too late to be what you might have been.",
  "You become what you believe.",
  "I would rather die of passion than of boredom.",
  "A truly rich man is one whose children run into his arms when his hands are empty.",
  "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.",
  "If you want your children to turn out well, spend twice as much time with them, and half as much money.",
  "Build your own dreams, or someone else will hire you to build theirs.",
  "The battles that count aren't the ones for gold medals. The struggles within yourself—the invisible battles inside all of us—that's where it's at.",
  "Education costs money. But then so does ignorance.",
  "The most important thing is to try and inspire people so that they can be great in whatever they want to do.",
  "Fall seven times and stand up eight.",
  "The real opportunity for success lies within the person and not in the job.",
  "Every accomplishment starts with the decision to try.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.",
  "Start where you are. Use what you have. Do what you can.",
  "The journey of a thousand miles begins with one step.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to discover the limits of the possible is to go beyond them into the impossible.",
  "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The person who moves a mountain begins by carrying away small stones.",
  "If you want to lift yourself up, lift up someone else.",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "Nothing is impossible, the word itself says 'I'm possible'!",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "You may encounter many defeats, but you must not be defeated.",
  "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
  "What we achieve inwardly will change outer reality.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Be yourself; everyone else is already taken.",
  "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.",
  "The purpose of our lives is to be happy.",
  "Get busy living or get busy dying.",
  "You have to expect things of yourself before you can do them.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You miss 100% of the shots you don't take.",
  "Whether you think you can or you think you can't, you're right.",
  "The future depends on what you do today.",
  "It always seems impossible until it's done.",
  "Act as if what you do makes a difference. It does.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Be the change that you wish to see in the world.",
  "Find out who you are and do it on purpose.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "The only true wisdom is in knowing you know nothing.",
  "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
  "Do what you can, with what you have, where you are.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "As we look ahead into the next century, leaders will be those who empower others.",
  "The best preparation for tomorrow is doing your best today.",
  "Happiness is not something readymade. It comes from your own actions.",
  "For every minute you are angry you lose sixty seconds of happiness.",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "Don't let the fear of losing be greater than the excitement of winning.",
  "If you want to make your dreams come true, the first thing you have to do is wake up.",
  "The only thing worse than being blind is having sight but no vision.",
  "The way to get started is to quit talking and begin doing.",
  "Don't let yesterday take up too much of today.",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character.",
  "If you are working on something exciting that you really care about, you don't have to be pushed. The vision pulls you.",
  "People who are serious about software should make their own hardware.",
  "Innovation distinguishes between a leader and a follower.",
  "The secret of getting ahead is getting started.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Only the paranoid survive.",
  "It's fine to celebrate success but it is more important to heed the lessons of failure.",
  "You can't connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future.",
  "If you haven't found it yet, keep looking. Don't settle.",
  "Stay hungry. Stay foolish.",
  "The people who are crazy enough to think they can change the world are the ones who do.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
  "The only way to do great work is to love what you do.",
  "Don't be trapped by dogma — which is living with the results of other people's thinking.",
  "Your time is limited, so don't waste it living someone else's life.",
  "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
  "Life is what happens to you while you're busy making other plans.",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "When you reach the end of your rope, tie a knot in it and hang on.",
  "Always remember that you are absolutely unique. Just like everyone else.",
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
  "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.",
  "It is during our darkest moments that we must focus to see the light.",
  "Whoever is happy will make others happy too.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "You will face many defeats in life, but never let yourself be defeated.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "In the end, it's not the years in your life that count. It's the life in your years.",
  "Never let the fear of striking out keep you from playing the game.",
  "Life is either a daring adventure or nothing at all.",
  "Many of life's failures are people who did not realize how close they were to success when they gave up.",
  "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
  "The only impossible journey is the one you never begin.",
  "In order to succeed, we must first believe that we can.",
  "A person who never made a mistake never tried anything new.",
  "The person who says it cannot be done should not interrupt the person who is doing it.",
  "There are no traffic jams along the extra mile.",
  "It is never too late to be what you might have been.",
  "You become what you believe.",
  "I would rather die of passion than of boredom.",
  "A truly rich man is one whose children run into his arms when his hands are empty.",
  "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.",
  "If you want your children to turn out well, spend twice as much time with them, and half as much money.",
  "Build your own dreams, or someone else will hire you to build theirs.",
  "The battles that count aren't the ones for gold medals. The struggles within yourself—the invisible battles inside all of us—that's where it's at.",
  "Education costs money. But then so does ignorance.",
  "The most important thing is to try and inspire people so that they can be great in whatever they want to do.",
  "Fall seven times and stand up eight.",
  "The real opportunity for success lies within the person and not in the job.",
  "Every accomplishment starts with the decision to try.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you have imagined.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.",
  "Start where you are. Use what you have. Do what you can.",
  "The journey of a thousand miles begins with one step.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The only way to discover the limits of the possible is to go beyond them into the impossible.",
  "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
  "The person who moves a mountain begins by carrying away small stones.",
  "If you want to lift yourself up, lift up someone else.",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "Nothing is impossible, the word itself says 'I'm possible'!",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "You may encounter many defeats, but you must not be defeated.",
  "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
  "What we achieve inwardly will change outer reality.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Be yourself; everyone else is already taken.",
  "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.",
  "The purpose of our lives is to be happy.",
  "Get busy living or get busy dying.",
  "You have to expect things of yourself before you can do them.",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
  "The only way to achieve the impossible is to believe it is possible.",
  "You miss 100% of the shots you don't take.",
  "Whether you think you can or you think you can't, you're right.",
  "The future depends on what you do today.",
  "It always seems impossible until it's done.",
  "Act as if what you do makes a difference. It does.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Be the change that you wish to see in the world.",
  "Find out who you are and do it on purpose.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "The only true wisdom is in knowing you know nothing.",
  "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
  "Do what you can, with what you have, where you are.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
  "As we look ahead into the next century, leaders will be those who empower others.",
  "The best preparation for tomorrow is doing your best today.",
  "Happiness is not something readymade. It comes from your own actions.",
  "For every minute you are angry you lose sixty seconds of happiness.",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "Don't let the fear of losing be greater than the excitement of winning.",
  "If you want to make your dreams come true, the first thing you have to do is wake up.",
  "The only thing worse than being blind is having sight but no vision.",
];

// Get daily motivational quote
// Returns the same quote for the entire day (based on day of year)
router.get('/daily', (req, res) => {
  try {
    // Get the day of the year (1-365/366)
    const now = new Date();
    const start = new Date(now.getFullYear(), 0, 0);
    const diff = now - start;
    const oneDay = 1000 * 60 * 60 * 24;
    const dayOfYear = Math.floor(diff / oneDay);
    
    // Use day of year to select a quote (modulo to cycle through all quotes)
    const quoteIndex = dayOfYear % motivationalQuotes.length;
    const quote = motivationalQuotes[quoteIndex];
    
    res.json({
      success: true,
      quote: quote,
      dayOfYear: dayOfYear,
      date: now.toISOString().split('T')[0], // YYYY-MM-DD format
    });
  } catch (error) {
    console.error('Get daily quote error:', error);
    res.status(500).json({ error: 'Internal server error' });
  }
});

// Get all quotes (optional, for admin/testing)
router.get('/all', (req, res) => {
  res.json({
    success: true,
    count: motivationalQuotes.length,
    quotes: motivationalQuotes,
  });
});

module.exports = router;
